# Generated by Django 4.2.5 on 2023-11-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Entry',
        ),
    ]
